.TH SHLCOV 1 "December 14, 2008"
.SH NAME
shlcov - produce HTML output of shell script execution coverage information
.SH DESCRIPTION
.PP
shlcov produces HTML output of execution coverage data for bourne shell and
bash scripts. It is used together with the
.I shcov
tool which captures runtime coverage data.
.SH SYNOPSIS
\fBshlcov [-s|--script-base=path] datadir outdir\fR
.TP
\fB\-s, --script-base=\fR \fIpath\fR
set the base path to lookup scripts sources (default is '')\fR
.PP
.SH HOMEPAGE
http://shcov.googlecode.com
.SH SEE ALSO
.BR shlcov (1)
.SH AUTHOR
This manual page was written by Simon Kagstrom <simon.kagstrom@gmail.com>

